services:
  neo4j:
    image: neo4j:enterprise

    container_name: neo4j_container

    volumes:
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/config:/config
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/plugins:/plugins
      - /home/diego/proyectos/portafolio/grafos-machine-learning/docker/import/:/import
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/test1234
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_memory_heap_initial__size: "4500m"
      NEO4J_server_memory_heap_max__size: "4500m"
      NEO4J_server_memory_pagecache_size: "3900m"
      NEO4J_db_memory_transaction_total_max: "4500m"
      
    ports:
      - "7474:7474"
      - "7687:7687"

    restart: unless-stopped

