
services:
  neo4j:
    image: neo4j:2025.12.1-enterprise
    container_name: neo4j_container
    volumes:
        - ${HOME}/neo4j/logs:/logs
        - ${HOME}/neo4j/config:/config
        - ${HOME}/neo4j/data:/data
        - ${HOME}/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'        
      NEO4J_server_memory_heap_initial__size: "2g"
      NEO4J_server_memory_heap_max__size: "2g"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
 